"$schema" = "../schema.json"

tz = "Europe/Paris"

[[jobs]]
name = "XXyyXX"
# ref: https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm#CIHBEEFA
crontab = "0/5 * * * * * *"
before = "echo \"Hello world!\""
exec = "echo \"I'm being executed!\""
after = "echo \"Bye world!\""
logs = "./example/job_1.log"

[[jobs]]
name = "disabled job"
enable = false
crontab = "0 0/2 * * * * *"
exec = "echo \"Im disabled\""

[[jobs]]
name = "YYwwYY"
duration = "5 s"
exec = "echo \"I'm being executed every 5 seconds!\""
